"""create agent tables and connection_type

Revision ID: 021f254aa976
Revises: 4085c2cea787
Create Date: 2026-09-29 09:33:55.183886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '021f254aa976'
down_revision: Union[str, None] = '4085c2cea787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_enrollment_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_enrollment_tokens_server_id'), 'agent_enrollment_tokens', ['server_id'], unique=False)
    op.create_index(op.f('ix_agent_enrollment_tokens_token_hash'), 'agent_enrollment_tokens', ['token_hash'], unique=False)
    op.create_index(op.f('ix_agent_enrollment_tokens_workspace_id'), 'agent_enrollment_tokens', ['workspace_id'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('agent_version', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('auth_token_hash', sa.String(length=255), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disconnected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('operating_system', sa.String(length=64), nullable=True),
    sa.Column('architecture', sa.String(length=64), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_auth_token_hash'), 'agents', ['auth_token_hash'], unique=False)
    op.create_index(op.f('ix_agents_server_id'), 'agents', ['server_id'], unique=True)
    op.create_index(op.f('ix_agents_workspace_id'), 'agents', ['workspace_id'], unique=False)
    op.create_table('agent_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_category', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_jobs_agent_id'), 'agent_jobs', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_jobs_request_id'), 'agent_jobs', ['request_id'], unique=False)
    op.create_index(op.f('ix_agent_jobs_server_id'), 'agent_jobs', ['server_id'], unique=False)
    op.create_index(op.f('ix_agent_jobs_workspace_id'), 'agent_jobs', ['workspace_id'], unique=False)
    op.add_column('servers', sa.Column('connection_type', sa.String(length=32), server_default='SSH', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servers', 'connection_type')
    op.drop_index(op.f('ix_agent_jobs_workspace_id'), table_name='agent_jobs')
    op.drop_index(op.f('ix_agent_jobs_server_id'), table_name='agent_jobs')
    op.drop_index(op.f('ix_agent_jobs_request_id'), table_name='agent_jobs')
    op.drop_index(op.f('ix_agent_jobs_agent_id'), table_name='agent_jobs')
    op.drop_table('agent_jobs')
    op.drop_index(op.f('ix_agents_workspace_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_server_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_auth_token_hash'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_agent_enrollment_tokens_workspace_id'), table_name='agent_enrollment_tokens')
    op.drop_index(op.f('ix_agent_enrollment_tokens_token_hash'), table_name='agent_enrollment_tokens')
    op.drop_index(op.f('ix_agent_enrollment_tokens_server_id'), table_name='agent_enrollment_tokens')
    op.drop_table('agent_enrollment_tokens')
    # ### end Alembic commands ###
