"""create_backup_tables

Revision ID: 10d45bbf57f8
Revises: f96c562c06f8
Create Date: 2026-09-29 07:45:56.257145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '10d45bbf57f8'
down_revision: Union[str, None] = 'f96c562c06f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('environment_id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('backup_type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=1024), nullable=False),
    sa.Column('destination', sa.String(length=1024), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('is_compressed', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_configs_created_at'), 'backup_configs', ['created_at'], unique=False)
    op.create_index(op.f('ix_backup_configs_environment_id'), 'backup_configs', ['environment_id'], unique=False)
    op.create_index(op.f('ix_backup_configs_server_id'), 'backup_configs', ['server_id'], unique=False)
    op.create_index(op.f('ix_backup_configs_workspace_id'), 'backup_configs', ['workspace_id'], unique=False)
    op.create_table('backups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('environment_id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('backup_config_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_name', sa.String(length=512), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('triggered_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['backup_config_id'], ['backup_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backups_backup_config_id'), 'backups', ['backup_config_id'], unique=False)
    op.create_index(op.f('ix_backups_created_at'), 'backups', ['created_at'], unique=False)
    op.create_index(op.f('ix_backups_environment_id'), 'backups', ['environment_id'], unique=False)
    op.create_index(op.f('ix_backups_server_id'), 'backups', ['server_id'], unique=False)
    op.create_index(op.f('ix_backups_status'), 'backups', ['status'], unique=False)
    op.create_index(op.f('ix_backups_workspace_id'), 'backups', ['workspace_id'], unique=False)
    op.create_table('backup_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('backup_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['backup_id'], ['backups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_logs_backup_id'), 'backup_logs', ['backup_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backup_logs_backup_id'), table_name='backup_logs')
    op.drop_table('backup_logs')
    op.drop_index(op.f('ix_backups_workspace_id'), table_name='backups')
    op.drop_index(op.f('ix_backups_status'), table_name='backups')
    op.drop_index(op.f('ix_backups_server_id'), table_name='backups')
    op.drop_index(op.f('ix_backups_environment_id'), table_name='backups')
    op.drop_index(op.f('ix_backups_created_at'), table_name='backups')
    op.drop_index(op.f('ix_backups_backup_config_id'), table_name='backups')
    op.drop_table('backups')
    op.drop_index(op.f('ix_backup_configs_workspace_id'), table_name='backup_configs')
    op.drop_index(op.f('ix_backup_configs_server_id'), table_name='backup_configs')
    op.drop_index(op.f('ix_backup_configs_environment_id'), table_name='backup_configs')
    op.drop_index(op.f('ix_backup_configs_created_at'), table_name='backup_configs')
    op.drop_table('backup_configs')
    # ### end Alembic commands ###
