"""create docker_compose_projects table

Revision ID: a38b1525a19c
Revises: 003_add_server_credentials
Create Date: 2026-09-29 05:47:26.391457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a38b1525a19c'
down_revision: Union[str, None] = '003_add_server_credentials'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('docker_compose_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('environment_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('project_name', sa.String(length=128), nullable=False),
    sa.Column('working_directory', sa.String(length=512), nullable=False),
    sa.Column('compose_file', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docker_compose_projects_environment_id'), 'docker_compose_projects', ['environment_id'], unique=False)
    op.create_index(op.f('ix_docker_compose_projects_server_id'), 'docker_compose_projects', ['server_id'], unique=False)
    op.create_index(op.f('ix_docker_compose_projects_workspace_id'), 'docker_compose_projects', ['workspace_id'], unique=False)
    op.drop_constraint(op.f('server_credentials_server_id_key'), 'server_credentials', type_='unique')
    op.drop_index(op.f('ix_server_credentials_server_id'), table_name='server_credentials')
    op.create_index(op.f('ix_server_credentials_server_id'), 'server_credentials', ['server_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_credentials_server_id'), table_name='server_credentials')
    op.create_index(op.f('ix_server_credentials_server_id'), 'server_credentials', ['server_id'], unique=False)
    op.create_unique_constraint(op.f('server_credentials_server_id_key'), 'server_credentials', ['server_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_docker_compose_projects_workspace_id'), table_name='docker_compose_projects')
    op.drop_index(op.f('ix_docker_compose_projects_server_id'), table_name='docker_compose_projects')
    op.drop_index(op.f('ix_docker_compose_projects_environment_id'), table_name='docker_compose_projects')
    op.drop_table('docker_compose_projects')
    # ### end Alembic commands ###
