"""create_deployment_tables

Revision ID: f96c562c06f8
Revises: a38b1525a19c
Create Date: 2026-09-29 06:15:39.023215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'f96c562c06f8'
down_revision: Union[str, None] = 'a38b1525a19c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('environment_id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('application_name', sa.String(length=255), nullable=False),
    sa.Column('working_directory', sa.String(length=1024), nullable=False),
    sa.Column('deployment_type', sa.String(length=64), nullable=False),
    sa.Column('branch', sa.String(length=255), nullable=True),
    sa.Column('repository_url', sa.String(length=1024), nullable=True),
    sa.Column('pre_deploy_steps', sa.JSON(), nullable=True),
    sa.Column('deploy_steps', sa.JSON(), nullable=True),
    sa.Column('post_deploy_steps', sa.JSON(), nullable=True),
    sa.Column('restart_service_name', sa.String(length=255), nullable=True),
    sa.Column('compose_project_name', sa.String(length=255), nullable=True),
    sa.Column('health_check_type', sa.String(length=64), nullable=True),
    sa.Column('health_check_url', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_configs_environment_id'), 'deployment_configs', ['environment_id'], unique=False)
    op.create_index(op.f('ix_deployment_configs_server_id'), 'deployment_configs', ['server_id'], unique=False)
    op.create_index(op.f('ix_deployment_configs_workspace_id'), 'deployment_configs', ['workspace_id'], unique=False)
    op.create_table('deployments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('environment_id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('deployment_config_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('triggered_by_user_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('commit_reference', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['deployment_config_id'], ['deployment_configs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_deployment_config_id'), 'deployments', ['deployment_config_id'], unique=False)
    op.create_index(op.f('ix_deployments_environment_id'), 'deployments', ['environment_id'], unique=False)
    op.create_index(op.f('ix_deployments_server_id'), 'deployments', ['server_id'], unique=False)
    op.create_index(op.f('ix_deployments_status'), 'deployments', ['status'], unique=False)
    op.create_index(op.f('ix_deployments_workspace_id'), 'deployments', ['workspace_id'], unique=False)
    op.create_table('deployment_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('deployment_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_logs_deployment_id'), 'deployment_logs', ['deployment_id'], unique=False)
    op.create_index(op.f('ix_deployment_logs_sequence'), 'deployment_logs', ['sequence'], unique=False)
    op.add_column('environments', sa.Column('is_protected', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('environments', 'is_protected')
    op.drop_index(op.f('ix_deployment_logs_sequence'), table_name='deployment_logs')
    op.drop_index(op.f('ix_deployment_logs_deployment_id'), table_name='deployment_logs')
    op.drop_table('deployment_logs')
    op.drop_index(op.f('ix_deployments_workspace_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_status'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_server_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_environment_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_deployment_config_id'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_deployment_configs_workspace_id'), table_name='deployment_configs')
    op.drop_index(op.f('ix_deployment_configs_server_id'), table_name='deployment_configs')
    op.drop_index(op.f('ix_deployment_configs_environment_id'), table_name='deployment_configs')
    op.drop_table('deployment_configs')
    # ### end Alembic commands ###
